image: atlassian/default-image:2

pipelines:
  branches:
    develop:
      - step:
          name: Build
          script:
            - pwd
            - ll
            - cp .env.dev .env
            - zip -x '.git/*' -r build.zip * .[^.]*
          artifacts:
            - build.zip

      - step:
          name: Upload to S3 Bucket
          services:
            - docker
          script:
            - pipe: atlassian/aws-code-deploy:1.4.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                COMMAND: upload
                APPLICATION_NAME: lance-betting-dev
                ZIP_FILE: build.zip

      - step:
          name: Deploy with CodeDeploy
          services:
            - docker
          script:
            - pipe: atlassian/aws-code-deploy:1.4.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                COMMAND: deploy
                APPLICATION_NAME: lance-betting-dev
                DEPLOYMENT_GROUP: lance-betting-dev-group
                FILE_EXISTS_BEHAVIOR: OVERWRITE
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
